### ISSUE TITLE
Lab 1 Materials

### ISSUE THREAD

**Issue by alexqaddourah** [alexqaddourah/msbx5500-spring-2020#1]
@deargle You can find my Lab1 Materials in my Lab1 Folder - inside this folder, I will label files/screenshots with what part of the Lab it is from.

**Comment by alexqaddourah** [comment]
@deargle any screenshots will be in Issues

**Comment by deargle** [comment]
No no, put the screenshots in the lab using this technique: https://gist.github.com/vinkla/dca76249ba6b73c5dd66a4e986df4c8d

**Comment by alexqaddourah** [comment]
I think I fixed it? I put the URL in the Read Me

**Comment by deargle** [comment]
I don't see any of your Lab 1 materials in your github Lab 1 folder -- did you "push to origin" from your laptop clone? 

Also, please don't put your work into the Lab1/readme.md that I made -- instead, make a new file. That way, you will be able to "pull" updates from my master into your lab1/readme.md

**Comment by alexqaddourah** [comment]
Okay I took it and put it in a new file in Lab 1 folder. But how do I push to origin? I didn't do that

**Comment by deargle** [comment]
Said Alex in another thread: 

> Lab 1 progress:
> 
> Applied to 3 jobs including Analytic Partners this afternoon. Will continue to apply to more this week. For me this week is "Job Week" lol with the 2 career fairs Wed and Thurs.
> Working through the Kaggle Tutorials. Trying to take my time with the ML ones so I can understand and take notes throughout.
> Skimming book tonight. Ive actually read only 2 chapters.
> 
> Everything else in the lab 1 is done

**Comment by deargle** [comment]
Shoot, there's no way that github will render your .ipynb.json, because it depends on sagemaker. Let's look for a way to export a markdown version of the ipynb, from sagemaker, since it's sagemaker where the aws-specific libraries are located

**Comment by deargle** [comment]
Where exactly are you with the ML labs?

You know, i'm going to reopen your other issue. This is hard.
